### ISSUE TITLE
Deadlock in GPSdEndpoint.stop()

### ISSUE THREAD

**Issue by msemtd** [taimos/GPSd4Java#16]
I always encounter a deadlock when GPSdEndpoint.stop() is called (Oracle JDK 1.7.0_51 on Windows 7) due to SocketThread.halt() calling this.reader.close().

Is there another way to make GPSd4Java stoppable and startable?

**Comment by hoegertn** [comment]
I will have a look at it

**Comment by hoegertn** [comment]
Merged the PR and will create a release if you need it asap.

**Comment by rapaza1** [comment]
Could you please share java example code on how to use gpsd4java? Looked all over the internet and can't find any. Thx a 1,000,000

**Comment by hoegertn** [comment]
You can have a look at the Tester class (https://github.com/taimos/GPSd4Java/blob/master/src/test/java/de/taimos/gpsd4java/test/Tester.java)

It connects to a gpsd on localhost.

**Comment by anhdenday** [comment]
Hi @hoegertn 
Could you please tell me how to get Longitude and Latitude by GPSd4Java.
Thanks you so much

**Comment by hoegertn** [comment]
Hi, just have a look at the class mentioned above. In line 86 you get a TPVObject if a new position was received. This object has getLatitude() and getLongitude() methods.

**Comment by anhdenday** [comment]
Hi thanks you @hoegertn ,
I will check it!
