### ISSUE TITLE
WATCH message not sent correctly on reconnect

### ISSUE THREAD

**Issue by renns** [taimos/GPSd4Java#24]
On reconnect to gpsd, the watch command is sent like this:

?WATCH=?WATCH={"enable":true,"json":true,"class":"WATCH"}

Notice the double "?WATCH=". The cause is in handleDisconnected().

this.syncCommand("?WATCH=" + lastWatch, WatchObject.class);
should be:
this.syncCommand(lastWatch, WatchObject.class);

**Comment by hoegertn** [comment]
fixed it. Will release a new version after some testing
