### ISSUE TITLE
GPSDEndpoint constructor fails if GPSD has not been started yet

### ISSUE THREAD

**Issue by balazs-zsoldos** [taimos/GPSd4Java#25]
In the constructor of the _GPSDEndpoint_ class the Socket to GPSD is opened. That means that GPSD must work before the constructor of the _GPSDEndpoint_ is called.

On the other hand, after successfully constructing the _GPSDEndpoint_ class, the client will reconnect if the GPSD goes away for an amount of time.

It would be nice if the GPSDEndpoint class was start-order independent, so the constructor would not open the socket, but network connection would be made only after start is called in a fail-safe mode.

Also, the start method of GPSDEndpoint sleeps for half a second before returning for no mentioned reason. If that sleep is there to be sure that some flag is set by the started Thread, lock objects should be used instead of sleeping so the startup thread of an application does not have to hang for half a second.

**Comment by balazs-zsoldos** [comment]
If you review it, I can create a PR with some modifications.

**Comment by hoegertn** [comment]
Hi, I am happy to improve the project. Feel free to open a PR.

**Comment by balazs-zsoldos** [comment]
Perfect. I (or one of my colleage will provide a PR). Let me ask you why there is a Thread.sleep in the start method of GPSEndpoint class? I guess there is a reason but without a comment, it is hard to find out what it waits for.

**Comment by hoegertn** [comment]
To be honest, I have no idea due to the missing comment. This happens when you look at code written by a younger self 6 years ago ;-)

**Comment by balazs-zsoldos** [comment]
@hoegertn Do you plan to give out a release? We are really waiting for a version with the patch. Thanks!

**Comment by hoegertn** [comment]
Current master is released as 1.9. 
Takes some time till it is available on Maven central.

**Comment by hoegertn** [comment]
@balazs-zsoldos  is this issue solved?

**Comment by balazs-zsoldos** [comment]
We have not tried it out in our production system embedded, but I think it should work (we tested this directly a lot). I close the issue and will create a separate one if anything is wrong.
