### ISSUE TITLE
Problems parsing timestamps

### ISSUE THREAD

**Issue by lbeuster** [taimos/GPSd4Java#28]
Hi, 
our gpsd does not return an ISO formatted date for timestamps (only tried TPV)  but instead the epoch seconds as a floating value. Does it make sense to add that case as a fallback to the AbstractResultParser.parseTimestamp or is our gpsd out of spec? As a workaround I subclassed the original ResultParser.

Best regards
Lars

**Comment by hoegertn** [comment]
I will look into it. What setup are you using?

Maybe the timestamp format can be made configurable.

**Comment by lbeuster** [comment]
We have gpsd 2.95 (protocol version 3.3). At the end I added the output of the POLL command.

Beside the format of the timestamp the poll-structure has a "timestamp" element while in the code the result parsers try to read a "time" element.

Maybe it's possible to have only one parser that can handle all gpsd versions so that the client code must not be changed in case of using a different gpsd.

I could not find a setting for the gpsd to change the timestamp format.

```
{"class":"VERSION","release":"2.95","rev":"2015-12-04T15:55:02","proto_major":3,"proto_minor":3}
{"class":"POLL",

"timestamp":1500970324.416,

"active":1,"fixes":[{"class":"TPV","tag":"GLL",
"device":"/dev/ttymxc2","time":1500970334.000,"ept":0.005,"lat":52.493798333,
"lon":13.384416833,"alt":71.900,"epx":31.964,"epy":13.796,"epv":30.797,"track":0.0000,
"speed":0.004,"climb":0.000,"eps":63.93,"mode":3}],"skyviews":[{"class":"SKY","tag":"GLL",
"device":"dev/ttymxc2","xdop":2.13,"ydop":0.92,"vdop":1.34,"tdop":1.03,"hdop":2.32,"gdop":2.87,
"pdop":2.68,"satellites":[{"PRN":2,"el":0,"az":0,"ss":28,"used":false},
{"PRN":12,"el":51,"az":89,"ss":35,"used":true},
{"PRN":24,"el":18,"az":156,"ss":38,"used":true},
{"PRN":25,"el":85,"az":337,"ss":36,"used":true},
{"PRN":31,"el":32,"az":307,"ss":39,"used":true}]}]}]}
```

**Comment by hoegertn** [comment]
The code change was in this commit: https://github.com/taimos/GPSd4Java/commit/7244f1673faac20c25082cfd34862c204fa877b8

Since then only gpsd >= 3.5 was supported.  I will have a look to see if some automagic is possible. Is there a reason to use such an old version?

**Comment by lbeuster** [comment]
Unfortunately there is a reason... we have to use an older embedded linux that can't be updated. 

I thought for older gpsd versions there is the LegacyResultParser, but doesn't seem to work either.

It's ok if the client doesn't want to support old gpsd versions because I can work around it, but maybe you could point that out in the README.

**Comment by hoegertn** [comment]
I think supporting an older version is currently not planned if you have a way around it.
But would https://github.com/taimos/GPSd4Java/tree/deduplicate_code be of any help? So subclassing the ResultParser would be much easier.

**Comment by lbeuster** [comment]
Now the parsers look much clearer ;) But does it make sense to keep the LegacyParser since you don't want to support older versions? E.g. it doesn't use the correct timestamp field ("time" instead of "timestamp" - or maybe the "timestamp" version it too old to support?).

If you want to keep it maybe you could add the legacy code to the regular ResultParser and use the old code as fallback, something like this:

```
if (jsonObjectHasField("sky")) {
   doSomethingWithField("sky"); // new version
} else {
   doSomethingWithField("skyviews"); // old version
}
```

With that the user doesn't have to care about anything - it just works without changes for all supported gpsd versions. You could also add a constructor with host + port, without parser (and without the backward compatible IOExceptions ;))

**Comment by hoegertn** [comment]
Ok, I implemented it. Do you have the chance to test the version in the branch?

**Comment by lbeuster** [comment]
Yes, thanks, I can test against our old gpsd.

Maybe you could get rid of the ugly IOException for the new constructor since it cannot be thrown anymore because of the reconnect-fix in 1.9. I guess you have to keep it for the old constructors that already existed in 1.8 for binary backward compatibility. But it would be nice to not have them in the new code.

**Comment by hoegertn** [comment]
Ok, I removed the exceptions on the new constructors and left it on the old one.

**Comment by lbeuster** [comment]
Everything works so far - except the original problem this ticket was for ;)

A fallback to parse the text as a double in the AbstractResultParser.parseTimestamp() would be nice if the formatter raises an exception.

**Comment by hoegertn** [comment]
```
if (json.has("time")) {
	poll.setTimestamp(this.parseTimestamp(json, "time"));
} else if (json.has("timestamp")) {
	poll.setTimestamp(json.optDouble("timestamp", Double.NaN));
}
```

It should read the timestamp field and parse it as double, or did I misunderstand your format?

**Comment by lbeuster** [comment]
All fields representing timestamps come as double values, not only the "timestamp" field in the poll.

**Comment by hoegertn** [comment]
OK, I added a fallback to double.

**Comment by lbeuster** [comment]
Thanks, works ;)

One thing. With the if/else-if it is now possible, that the setter is not being called. Especially for list properties it's now possible that you have a null list at the end (if both field alternatives are not present). Before you always had a non-null list, even if the field was not present. Maybe replace the else-if with a simple else?

**Comment by hoegertn** [comment]
If the field is not present wouldn't this lead to the setter being called with null, too?

**Comment by lbeuster** [comment]
I guess it depends on the type. At least for list objects the setter is called with an empty list if the field is not present (parseObjectArray() does that).

```
poll.setSkyviews(this.parseObjectArray(json.optJSONArray("skyviews"), SKYObject.class));
```

**Comment by hoegertn** [comment]
ok, will add another else block to set an empty list. Then it is explicit.

**Comment by lbeuster** [comment]
even better ;)

**Comment by hoegertn** [comment]
comitted. If this is it I will merge the complete branch to get all changes to master.

**Comment by lbeuster** [comment]
Yes, that's it - and the not planned support for older versions it (at least partially) there ;)

Thank you!
